name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Ubuntu server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash -l -c '
              export NPM_CONFIG_PREFIX=$HOME/.npm-global
              export PATH="$HOME/.npm-global/bin:$HOME/.local/share/pnpm:$PATH"
          
              mkdir -p $HOME/.npm-global
          
              git config --global --add safe.directory /home/minjae/blog-nextjs
              cd /home/minjae/blog-nextjs
              git pull origin main
          
              command -v pnpm >/dev/null 2>&1 || npm install -g pnpm
              command -v pm2 >/dev/null 2>&1 || npm install -g pm2
          
              pnpm install
              pnpm build
              pm2 delete blognext || true
              pm2 start "pnpm start" --name blognext
            '
